### ISSUE TITLE
Search option is not working in cloud foundry documentation page

### ISSUE THREAD

**Issue by faizansyed66** [cloudfoundry/docs-book-cloudfoundry#134]
Search option is not working in cloud foundry documentation page (https://docs.cloudfoundry.org/), whenever we search any keyword its not showing any result.

**Comment by anita-flegg** [comment]
Yes, that had to be turned off because Elastic search is not working and management has decided not to renew support or upgrade. I fought it, but I lost  -- sorry about that.
The justification I was given is that most people find the topic they want using the browser search bar.
I usually go to the main CF docs page and do a ctrl/F search to find the right topic. 
https://docs.cloudfoundry.org/#read-the-docs
Hope that helps. :)
